name: pr test

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: |
            DATE=`date +"%Y%m%d"`
            "Release_$DATE"
