name: rele

on:
  push:
    branches:
      - release-*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Variable
        run: |
          DATE=`date +"%Y%m%d"`
          TITLE="Release_$DATE"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: $TITLE
          commit-message: update changelog
          body: Update changelog to reflect release changes
          branch: develop
          base: main
